galaxy_info:
  author: Ryan Sinnet
  description: Install docker-compose, kind, kubectl, etc.
  company: Miso Robotics
  license: MIT
  min_ansible_version: 2.9
  platforms: # https://galaxy.ansible.com/api/v1/platforms/
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: []
dependencies: []
