--- # tasks file for poetry
- name: Install dependencies for Poetry
  become: yes
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-setuptools
      - python3-venv
      - python3-wheel

- name: Download install-poetry.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
    dest: "{{ansible_facts.env.HOME}}/install-poetry.py"

- name: Install Poetry
  command: python {{ansible_facts.env.HOME}}/install-poetry.py

- name: Remove install-poetry.py
  ansible.builtin.file:
    path: "{{ansible_facts.env.HOME}}/install-poetry.py"
    state: absent

- name: Install bash completion for poetry
  include_role: { role: shell-completion }
  vars:
    user_completion_args:
      poetry: completions bash
  tags: shell-completion
