--- # tasks file for ansible-completion
- name: Install bash-completion
  become: yes
  ansible.builtin.apt: { name: bash-completion }
- name: Install bash completion for ansible command-line tools
  become: yes
  ansible.builtin.get_url:
    url: >-
      https://raw.githubusercontent.com/dysosmus/ansible-completion/master/{{item}}-completion.bash
    dest: >-
      /etc/bash_completion.d/{{item}}
  loop:
    - ansible
    - ansible-doc
    - ansible-galaxy
    - ansible-playbook
    - ansible-pull
    - ansible-vault
