galaxy_info:
  author: Ryan Sinnet
  description: Install the latest version of CMake
  company: Miso Robotics
  license: MIT
  min_ansible_version: 2.9
  platforms: # https://galaxy.ansible.com/api/v1/platforms/
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags: []
dependencies: []
